// eslint-disable-next-line no-magic-numbers
export const DEFAULT_KERNEL_STRETCH_FACTOR_RANGE = [0.8, 2.5] as const
export const DEFAULT_KERNEL_STRETCH_FACTOR_SEARCH_STEP_SIZE = 0.1
export const DEFAULT_MINIMAL_MODALITY_SIZE = 3
export const DEFAULT_MINIMUM_USED_TO_TOTAL_SAMPLES_RATIO = 0.6
export const DEFAULT_STDEV_DIFF_PENALTY_FACTOR = 1
export const DEFAULT_DISCARDED_DATA_PENALTY_FACTOR = 0.5
export const DEFAULT_HIGH_POOLED_STDEV_PENALTY_FACTOR = 1
export const DEFAULT_HIGH_MEAN_DISTANCE_RATIO_PENALTY_FACTOR = 1
export const DEFAULT_NOISE_SIZE_BONUS_FACTOR = 0.2
export const DEFAULT_MODALITY_COUNT_SIMILARITY_BONUS_FACTOR = 1
export const DEFAULT_OUTCOME_FREQUENCY_PVALUE_ADJUSTMENT_FACTOR = 0.5
// matches Cohen's D of 0.5 (medium size change)
export const DEFAULT_MINIMAL_ABSOLUTE_CHANGE_PROBABILITY = 0.276

export const DEFAULT_CONFIDENCE_LEVEL = 0.95
export const DEFAULT_MODALITY_SPLIT_TO_NOISE_RATIO = 0.8
export const DEFAULT_NOISE_VALUES_PER_SAMPLE = 2
export const DEFAULT_COMPARISON_QUALITY_WEIGHTING_OPTIONS = {
  stdevDiffPenaltyFactor: DEFAULT_STDEV_DIFF_PENALTY_FACTOR,
  discardedDataPenaltyFactor: DEFAULT_DISCARDED_DATA_PENALTY_FACTOR,
  highPooledStdevPenaltyFactor: DEFAULT_HIGH_POOLED_STDEV_PENALTY_FACTOR,
  highMeanDistanceRatioPenaltyFactor:
    DEFAULT_HIGH_MEAN_DISTANCE_RATIO_PENALTY_FACTOR,
  noiseSizeBonusFactor: DEFAULT_NOISE_SIZE_BONUS_FACTOR,
  modalityCountSimilarityBonusFactor:
    DEFAULT_MODALITY_COUNT_SIMILARITY_BONUS_FACTOR,
}
